server:
  port: 8083

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/softinventorydb
    username: kabiruahmed
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

  config:
    import: optional:configserver:http://localhost:8888

  springdoc:
    packagesToScan: com.hamsoft.productservice