server:
  port: 8765

spring:
  application:
    name: admin-service

  cloud:
      config:
        uri: http://localhost:8888

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/